export const authors: string[] = [
  'Dawid Bessman',
  'Antoni Cieśliński',
  'Witold Cieśliński',
  'Paweł Cissewski',
  'Mateusz Dąbek',
  'Jan Drzewiecki',
  'Weronika Gozdera',
  'Wojciech Gulan',
  'Krzysztof Janikowski',
  'Wojciech Kowalczyk',
  'Michał Leszczyński',
  'Maciej Mróz',
  'Wiktor Owerczuk',
  'Juliusz Parchem',
  'Marcin Płużyński',
  'Bartosz Potrykus',
  'Maksymilian Sobolewski',
  'Marta Sulżycka',
  'Aleksandra Swastek',
  'Jakub Swastek',
  'Małgorzata Swastek',
  'Marta Urbaniak',
  'Ariuna Wejner',
]
