nameOverride: "watchdog-frontend"
fullnameOverride: "watchdog-frontend"
    
app-template:
  nameOverride: "watchdog-frontend"
  fullnameOverride: "watchdog-frontend"
  replicaCount: 1

  service:
    type: ClusterIP
    targetPort: 3000
    port: 3000
  
  environmentalVariables:
    enabled: true
    globalVariables:
      DOCKER_CONTEXT_PATH: '/'

  ingress:
    enabled: true
    annotations: 
      appgw.ingress.kubernetes.io/ssl-redirect: "true"

